/*
 * TIMER1_Program.c
 *
 *  Created on: Feb 23, 2024
 *      Author: Abdelrahman (Ta'laab) Mohammed
 *		Github: https://github.com/AbdelrahmanMohammed002
 */

#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"

#include "TIMER1_Interface.h"
#include "TIMER1_Private.h"
#include "TIMER1_Config.h"

void (*TIMER1A_CTC_Call_Back)(void) = NULL;
void (*TIMER1_OVF_Call_Back)(void) = NULL;
void (*TIMER1B_CTC_Call_Back)(void) = NULL;
void (*TIMER1_ICU_Call_Back)(void) = NULL;

void MTIMER1_vInit(void) {

#ifdef TIMER1_CHANNEL_A_ENABLE

#if TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_NORMAL
	CLR_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1B, WGM12);
	CLR_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_8BIT
	SET_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1B, WGM12);
	CLR_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_9BIT
		CLR_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_10BIT
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_CTC_OCR1A
	CLR_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1B, WGM12);
	CLR_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_8BIT
		SET_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_9BIT
		CLR_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_10BIT
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_FREQUANCY_CORRECT_ICR1
		CLR_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_FREQUANCY_CORRECT_OCR1A
		SET_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_ICR1
		CLR_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_OCR1A
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_CTC_ICR1
		CLR_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_ICR1
	CLR_BIT(TCCR1A, WGM10);
	SET_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1B, WGM12);
	SET_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_A_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_OCR1A
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#endif

#if	TIMER1_u8_CHANNEL_A_OUTPUT_MODE == TIMER1_OC1_DISCONNECTED
	CLR_BIT(TCCR1A, COM1A0);
	CLR_BIT(TCCR1A, COM1A1);
#elif TIMER1_u8_CHANNEL_A_OUTPUT_MODE == TIMER1_u8_OC1_TOGGLE
			SET_BIT(TCCR1A,COM1A0);
			CLR_BIT(TCCR1A,COM1A1);
		#elif TIMER1_u8_CHANNEL_A_OUTPUT_MODE == TIMER1_u8_OC1_CLEAR
	CLR_BIT(TCCR1A, COM1A0);
	SET_BIT(TCCR1A, COM1A1);
#elif TIMER1_u8_CHANNEL_A_OUTPUT_MODE == TIMER1_u8_OC1_SET
			SET_BIT(TCCR1A,COM1A0);
			SET_BIT(TCCR1A,COM1A1);
		#endif
#endif

#ifdef TIMER1_CHANNEL_B_ENABLE

#if TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_NORMAL
	CLR_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1B, WGM12);
	CLR_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_8BIT
	SET_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1B, WGM12);
	CLR_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_9BIT
		CLR_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_10BIT
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_CTC_OCR1A
		CLR_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_8BIT
		SET_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_9BIT
		CLR_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_10BIT
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		CLR_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_FREQUANCY_CORRECT_ICR1
		CLR_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_FREQUANCY_CORRECT_OCR1A
		SET_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_ICR1
		CLR_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_PWM_PHASE_CORRECT_OCR1A
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		CLR_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_CTC_ICR1
		CLR_BIT(TCCR1A,WGM10);
		CLR_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_ICR1
	CLR_BIT(TCCR1A, WGM10);
	SET_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1B, WGM12);
	SET_BIT(TCCR1B, WGM13);
#elif TIMER1_u8_CHANNEL_B_WAVEFORM_MODE == TIMER1_u8_FAST_PWM_OCR1A
		SET_BIT(TCCR1A,WGM10);
		SET_BIT(TCCR1A,WGM11);
		SET_BIT(TCCR1B,WGM12);
		SET_BIT(TCCR1B,WGM13);
	#endif

#if	TIMER1_u8_CHANNEL_B_OUTPUT_MODE == TIMER1_OC1_DISCONNECTED
	CLR_BIT(TCCR1A, COM1B0);
	CLR_BIT(TCCR1A, COM1B1);
#elif TIMER1_u8_CHANNEL_B_OUTPUT_MODE == TIMER1_u8_OC1_TOGGLE
			SET_BIT(TCCR1A,COM1B0);
			CLR_BIT(TCCR1A,COM1B1);
		#elif TIMER1_u8_CHANNEL_B_OUTPUT_MODE == TIMER1_u8_OC1_CLEAR
	CLR_BIT(TCCR1A, COM1B0);
	SET_BIT(TCCR1A, COM1B1);
#elif TIMER1_u8_CHANNEL_B_OUTPUT_MODE == TIMER1_u8_OC1_SET
			SET_BIT(TCCR1A,COM1B0);
			SET_BIT(TCCR1A,COM1B1);
		#endif
#endif

#if TIMER1_u8_PRESCALLER == TIMER1_u8_STOP
		CLR_BIT(TCCR1B,CS10);
		CLR_BIT(TCCR1B,CS11);
		CLR_BIT(TCCR1B,CS12);
	#elif TIMER1_u8_PRESCALLER == TIMER1_u8_DIV_BY_1
	SET_BIT(TCCR1B, CS10);
	CLR_BIT(TCCR1B, CS11);
	CLR_BIT(TCCR1B, CS12);
#elif TIMER1_u8_PRESCALLER == TIMER1_u8_DIV_BY_8
	CLR_BIT(TCCR1B, CS10);
	SET_BIT(TCCR1B, CS11);
	CLR_BIT(TCCR1B, CS12);
#elif TIMER1_u8_PRESCALLER == TIMER1_u8_DIV_BY_64
		SET_BIT(TCCR1B,CS10);
		SET_BIT(TCCR1B,CS11);
		CLR_BIT(TCCR1B,CS12);
	#elif TIMER1_u8_PRESCALLER == TIMER1_u8_DIV_BY_256
		CLR_BIT(TCCR1B,CS10);
		CLR_BIT(TCCR1B,CS11);
		SET_BIT(TCCR1B,CS12);
	#elif TIMER1_u8_PRESCALLER == TIMER1_u8_DIV_BY_1024
	SET_BIT(TCCR1B, CS10);
	CLR_BIT(TCCR1B, CS11);
	SET_BIT(TCCR1B, CS12);
#endif

#if TIMER1_u8_INPUT_CAPTURE == TIMER1_u8_RISING_INPUT_CAPTURE
		SET_BIT(TCCR1B,ICES1);
	#elif TIMER1_u8_INPUT_CAPTURE == TIMER1_u8_FALLING_INPUT_CAPTURE
	CLR_BIT(TCCR1B, ICES1);
#endif

}

void MTIMER1_vDisInit(void) {
	TCCR1A = 0;
	TCCR1B = 0;
}

void MTIMER1_vSetOVFRegister(u16 A_u16Value) {
	TCNT1 = A_u16Value;
}
void MTIMER1_vChannelASetCTCRegister(u16 A_u16Value) {
	OCR1A = A_u16Value;
}
void MTIMER1_vChannelBSetCTCRegister(u16 A_u16Value) {
	OCR1B = A_u16Value;
}
void MTIMER1_vSetICR1Value(u16 A_u16Val) {
	ICR1 = A_u16Val;
}
u16 MTIMER1_u16InputCaptureValue(void) {
	return ICR1;
}

void MTIMER1_vEnableOVFINT(void) {
	SET_BIT(TIMSK, TOIE1);
}
void MTIMER1_vDisableOVFINT(void) {
	CLR_BIT(TIMSK, TOIE1);
}
void MTIMER1_vClearOVFFlag(void) {
	SET_BIT(TIFR, TOV1);
}

void MTIMER1_vChannelAEnableCTCINT(void) {
	SET_BIT(TIMSK, OCIE1A);

}

void MTIMER1_vChannelADisableCTCINT(void) {
	CLR_BIT(TIMSK, OCIE1A);
}
void MTIMER1_vChannelAClearCTCFlag(void) {
	SET_BIT(TIFR, OCF1A);
}

void MTIMER1_vChannelBEnableCTCINT(void) {
	SET_BIT(TIMSK, OCIE1B);

}
void MTIMER1_vChannelBDisableCTCINT(void) {
	CLR_BIT(TIMSK, OCIE1B);

}
void MTIMER1_vChannelBClearCTCFlag(void) {
	SET_BIT(TIFR, OCF1B);

}

void MTIMER1_vEnableInputCaptureINT(void) {
	SET_BIT(TIMSK, TICIE1);

}
void MTIMER1_vDisableInputCaptureINT(void) {
	CLR_BIT(TIMSK, TICIE1);

}
void MTIMER1_vClearInputCaptureFlag(void) {
	SET_BIT(TIFR, ICF1);
}

void MTIMER1_vChannelAForceOutputCompare(void) {
	SET_BIT(TCCR1A, FOC1A);
}
void MTIMER1_vChannelBForceOutputCompare(void) {
	SET_BIT(TCCR1A, FOC1B);

}

void MTIMER1_vSetOVFCallBack(void (*CallBack)(void)) {
	if (CallBack != NULL) {
		TIMER1_OVF_Call_Back = CallBack;
	}
}
void MTIMER1_vChannelASetCTCCallBack(void (*CallBack)(void)) {
	if (CallBack != NULL) {
		TIMER1A_CTC_Call_Back = CallBack;
	}
}
void MTIMER1_vChannelBSetCTCCallBack(void (*CallBack)(void)) {
	if (CallBack != NULL) {
		TIMER1B_CTC_Call_Back = CallBack;
	}
}
void MTIMER1_vSetInputCaptureCallBack(void (*CallBack)(void)) {
	if (CallBack != NULL) {
		TIMER1_ICU_Call_Back = CallBack;
	}
}

void __vector_6(void) {
	if (TIMER1_ICU_Call_Back != NULL)
		TIMER1_ICU_Call_Back();
	MTIMER1_vClearInputCaptureFlag();
}

void __vector_7(void) {
	if (TIMER1A_CTC_Call_Back != NULL)
		TIMER1A_CTC_Call_Back();
	MTIMER1_vChannelAClearCTCFlag();
}

void __vector_8(void) {
	if (TIMER1B_CTC_Call_Back != NULL)
		TIMER1B_CTC_Call_Back();
	MTIMER1_vChannelBClearCTCFlag();
}

void __vector_9(void) {
	if (TIMER1_OVF_Call_Back != NULL)
		TIMER1_OVF_Call_Back();
	MTIMER1_vClearOVFFlag();
}

